# mkdocs.yml

site_name: "Glossário de IA no Setor Público"
site_description: "Glossário de Inteligência Artificial voltado ao setor público."
site_author: "Hugo Souto e colaboradores"
repo_url: "https://github.com/hugosouto/glossario-ia-setor-publico"
edit_uri: "blob/main/docs"
docs_dir: "glossario"
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Introdução: introducao.md
  - Conceitos:
      - "Inteligência Artificial": conceitos/ia.md
      - "Aprendizado de Máquina": conceitos/aprendizado-maquina.md
      - "Ética em IA": conceitos/etica.md
      - "Governança de Dados": conceitos/governanca-dados.md
  - Referências: referencias.md
  - Sobre: sobre.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.betterem

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - scripts/custom.js

plugins:
  - search:
      lang: pt
